name: 监测A股大盘行情

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 1-8 * * 1-5'

jobs:

  fetch:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          pip install chinesecalendar

      - name: Run script
        env:
          QYWECHAT_KEY: ${{ secrets.QYWECHAT_KEY }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python main.py

      - name: Commit state
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add alert_state.json
          git commit -m "update state" || echo "no change"
          git push
